name = "overlaysystem"
main = "src/index.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./public"

[[d1_databases]]
binding = "DB"
database_name = "overlay-db"
database_id = "9ad1b17a-ebfc-4922-a1f6-ed2e3bd6267d"

[[kv_namespaces]]
binding = "SESSIONS"
id = "f962df1a994345578ea956ac70fa64f3"

[vars]
ADMIN_SECRET = "K9#mX2$vQ7@nL4&wR8!pT3^jY6*hN5"

[build]
command = "npx wrangler deploy"
